### ISSUE TITLE
Beads won't load audio file.

### ISSUE THREAD

**Issue by fadelakin** [TimboKZ/ActiveVisualiser#2]
Everytime I load an audio file, it tells me that beads has a problem loading the audio file. I checked to see if the file exists, which it does but Beads won't open it. 

It always says 

```
Exception in thread "main" java.io.IOException: Problem loading file (class=class net.beadsproject.beads.data.audiofile.JavaSoundAudioFile) /Users/Fisher/Documents/Programming/Processing/DAV/coco.mp3, Could not read audio file: /Users/Fisher/Documents/Programming/Processing/DAV/coco.mp3
    at net.beadsproject.beads.data.Sample.loadAudioFile(Unknown Source)
    at net.beadsproject.beads.data.Sample.<init>(Unknown Source)
```

**Comment by fadelakin** [comment]
Actually. I figured out that changing the file format to a .wav file fixes the problem. Don't know why Beads won't accept .mp3 files.
